config/routes.rb
AncestralBridge::Application.routes.draw do
  get "home/index"
  root :to => "home#index"
  resources :users
  resource :session
  resource :familysearch_accounts
  resources :trees
  match '/register' => "users#new", :as => "register"
  match '/login' => "sessions#new", :as => "login"
  match '/logout' => "sessions#destroy", :as => "logout"
  match '/connect' => "home#connect", :as => "connect"
  match '/link_fsa' => "familysearch_accounts#new", :as => "link_fsa"
  match '/test_fsa_connection' => "familysearch_accounts#test_connection", :as => "test_fsa_connection"
  match '/trees/:id/sync' => "trees#sync", :as => "sync_tree"

end

app/models/tree.rb
class Tree < ActiveRecord::Base
  attr_accessible :user_id, :name, :person_id

  belongs_to :user
  has_one :person
  has_many :people
  has_many :familysearch_identifiers, :through => :people

  def getRoot
    person = Person.new
    unless person_id.nil?
      person = Person.find(person_id)
    end
    return person
  end
end

app/controllers/trees_controller.rb
class TreesController < ApplicationController
  before_filter :require_login

  # GET /trees
  # GET /trees.json
  def index
    @trees = current_user.trees.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @trees }
    end
  end

  # GET /trees/1
  # GET /trees/1.json
  def show
    @tree = find_tree(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tree }
    end
  end

  # GET /trees/new
  # GET /trees/new.json
  def new
    @tree = Tree.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tree }
    end
  end

  # GET /trees/1/edit
  def edit
    @tree = find_tree(params[:id])
  end

  # POST /trees
  # POST /trees.json
  def create
    @tree = current_user.trees.build(params[:tree])

    respond_to do |format|
      if @tree.save
        format.html { redirect_to @tree, notice: 'Tree was successfully created.' }
        format.json { render json: @tree, status: :created, location: @tree }
      else
        format.html { render action: "new" }
        format.json { render json: @tree.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /trees/1
  # PUT /trees/1.json
  def update
    @tree = find_tree(params[:id])

    respond_to do |format|
      if @tree.update_attributes(params[:tree])
        format.html { redirect_to @tree, notice: 'Tree was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tree.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trees/1
  # DELETE /trees/1.json
  def destroy
    @tree = find_tree(params[:id])
    @tree.destroy

    respond_to do |format|
      format.html { redirect_to trees_url }
      format.json { head :no_content }
    end
  end

  def sync
    @tree = find_tree(params[:id])
    if logged_in?
      fs_account = current_user.familysearch_account
      unless fs_account.nil?
        if fs_account.fetch_session_id?
          fs_account.fetch_tree(@tree)
        end
      end
    end
  end
  
  protected

  def find_tree(id)
    begin
      return current_user.trees.find(id)
    rescue ActiveRecord::RecordNotFound
      redirect_to trees_path, notice: "Couldn't find tree with id '"+params[:id]+"'."
    end
  end
end

app/helpers/trees_helper.rb
module TreesHelper
end

app/views/trees/_form.html.erb
<%= form_for(@tree) do |f| %>
  <% if @tree.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tree.errors.count, "error") %> prohibited this tree from being saved:</h2>

      <ul>
      <% @tree.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
 <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/trees/edit.html.erb
<h1>Editing tree</h1>

<%= render 'form' %>

<%= link_to 'Show', @tree %> |
<%= link_to 'Back', trees_path %>

app/views/trees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing trees</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Root Person</th>
    <th>Size</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @trees.each do |tree| %>
  <tr>
    <td><%= tree.name %></td>
    <td><%= if tree.getRoot().nil?
              link_to 'Sync', sync_tree_path(tree)
            else
              tree.getRoot().name;
            end %></td>
    <td><%= tree.people.length %></td>
    <td><%= link_to 'Show', tree %></td>
    <td><%= link_to 'Edit', edit_tree_path(tree) %></td>
    <td><%= link_to 'Destroy', tree, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Tree', new_tree_path %>

app/views/trees/new.html.erb
<h1>New tree</h1>

<%= render 'form' %>

<%= link_to 'Back', trees_path %>

app/views/trees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @tree.name %>
</p>

<p>
  <b>Person:</b>
  <%= @tree.person_id %>
</p>


<%= link_to 'Edit', edit_tree_path(@tree) %> |
<%= link_to 'Back', trees_path %>