config/routes.rb
AncestralBridge::Application.routes.draw do
  get "home/index"
  root :to => "home#index"
  resources :users
  resource :session
  resource :familysearch_accounts
  resources :trees
  match '/register' => "users#new", :as => "register"
  match '/login' => "sessions#new", :as => "login"
  match '/logout' => "sessions#destroy", :as => "logout"
  match '/connect' => "home#connect", :as => "connect"
  match '/link_fsa' => "familysearch_accounts#new", :as => "link_fsa"
  match '/test_fsa_connection' => "familysearch_accounts#test_connection", :as => "test_fsa_connection"
  match '/trees/:id/sync' => "trees#sync", :as => "sync_tree"

end

app/models/familysearch_account.rb
class FamilysearchAccount < ActiveRecord::Base
  attr_accessible :password, :session_id, :session_update, :user_id, :username

  validates :username,
    :presence => true,
    :length => { :within => 4..50 }

  validates :password,
    :presence => true,
    :length => { :within => 4..50 }

  belongs_to :user

  def fetch_session_id?
    if session_update.nil? || session_id.nil? || (session_update < (Time.now - 3.hour))
      id = FamilysearchApi::query_session_id(username, password)
      unless id == false
        update_attributes({ :session_id => id, :session_update => Time.now })
        return true
      end
    else
      return true
    end
    return false
  end

  def fetch_tree(tree, pid = nil)
    if fetch_session_id?
      communicator = FamilysearchApi::check_communicator(username, password)
      return FamilysearchApi::fetch_tree(communicator, tree, pid)
    end
    nil
  end
end

app/controllers/familysearch_accounts_controller.rb
class FamilysearchAccountsController < ApplicationController
  before_filter :require_login
 
  def test_connection
    unless has_fsa?
      return redirect_to link_fsa_path
    end
  end

  # GET /familysearch_accounts/new
  # GET /familysearch_accounts/new.json
  def new
    @familysearch_account = FamilysearchAccount.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @familysearch_account }
    end
  end

  # POST /familysearch_accounts
  # POST /familysearch_accounts.json
  def create
    if has_fsa?
      @familysearch_account = find_fsa
      @familysearch_account.username = params[:familysearch_account][:username]
      @familysearch_account.password = params[:familysearch_account][:password]
    else
      @familysearch_account = current_user.create_familysearch_account(params[:familysearch_account])
    end

    respond_to do |format|
      if @familysearch_account.save
        format.html { redirect_to test_fsa_connection_path, notice: 'Familysearch account was successfully created.' }
        format.json { render json: @familysearch_account, status: :created, location: @familysearch_account }
      else
        format.html { render action: "new" }
        format.json { render json: @familysearch_account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /familysearch_accounts/1
  # DELETE /familysearch_accounts/1.json
  def destroy
    @familysearch_account = find_fsa
    @familysearch_account.destroy

    respond_to do |format|
      format.html { redirect_to link_fsa_path }
      format.json { head :no_content }
    end
  end

  def find_fsa
    begin
      return current_user.familysearch_account
    rescue ActiveRecord::RecordNotFound
      redirect_to connect_path, notice: "Couldn't find your familysearch.org credentials."
    end
  end
end

app/helpers/familysearch_accounts_helper.rb
module FamilysearchAccountsHelper
end

app/views/familysearch_accounts/_form.html.erb
<%= form_for(@familysearch_account) do |f| %>
  <% if @familysearch_account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@familysearch_account.errors.count, "error") %> prohibited these Familysearch.org credentials from being saved:</h2>

      <ul>
      <% @familysearch_account.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.text_field :password %>
  </div>
  <div class="actions">
    <%= f.submit "Save"%>
  </div>
<% end %>

app/views/familysearch_accounts/edit.html.erb
<h1>Editing familysearch_account</h1>

<%= render 'form' %>

<%= link_to 'Show', @familysearch_account %> |
<%= link_to 'Back', familysearch_accounts_path %>

app/views/familysearch_accounts/index.html.erb
<h1>Listing familysearch_accounts</h1>

<table>
  <tr>
    <th>User</th>
    <th>Username</th>
    <th>Password</th>
    <th>Session</th>
    <th>Session update</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @familysearch_accounts.each do |familysearch_account| %>
  <tr>
    <td><%= familysearch_account.user_id %></td>
    <td><%= familysearch_account.username %></td>
    <td><%= familysearch_account.password %></td>
    <td><%= familysearch_account.session_id %></td>
    <td><%= familysearch_account.session_update %></td>
    <td><%= link_to 'Show', familysearch_account %></td>
    <td><%= link_to 'Edit', edit_familysearch_account_path(familysearch_account) %></td>
    <td><%= link_to 'Destroy', familysearch_account, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Familysearch account', new_familysearch_account_path %>

app/views/familysearch_accounts/new.html.erb
<h1>New familysearch_account</h1>

<%= render 'form' %>

<%= link_to 'Back', familysearch_accounts_path %>

app/views/familysearch_accounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @familysearch_account.user_id %>
</p>

<p>
  <b>Username:</b>
  <%= @familysearch_account.username %>
</p>

<p>
  <b>Password:</b>
  <%= @familysearch_account.password %>
</p>

<p>
  <b>Session:</b>
  <%= @familysearch_account.session_id %>
</p>

<p>
  <b>Session update:</b>
  <%= @familysearch_account.session_update %>
</p>


<%= link_to 'Edit', edit_familysearch_account_path(@familysearch_account) %> |
<%= link_to 'Back', familysearch_accounts_path %>

app/views/familysearch_accounts/test_connection.html.erb
Test Connection